[package]
name = "lnix-nix-dispatcher"
version = "0.2.0"
edition = "2024"
description = "Nix command dispatcher for LazyNix"
license = "MIT"
repository = "https://github.com/shunsock/lazynix"

[dependencies]
thiserror = "1.0"
